<template>
  <v-layout>
    <v-flex text-xs-center>

      <blockquote class="blockquote">

      <v-card>
        <v-card-text>
          <h1>Week's Menu</h1>
          <h3>06/05/19-11/05/19</h3>
          <table style="width:100%">

              <tr>
                  <th>Breakfast</th>
                  <th>Monday</th>
              </tr>
              <tr>
                <td></td>
                <td>Meal#1</td>
              </tr>
              <tr>
                <td></td>
                <td>Meal#2</td>
              </tr>
              <tr>
                <td></td>
                <td>Meal#3</td>
              </tr>
                <tr>
                  <th>Lunch</th>
                  <td>Meal#1</td>
                </tr>
                <tr>
                  <td></td>
                  <td>Meal#2</td>
                </tr>
                <tr>
                  <td></td>
                  <td>Meal#3</td>
                </tr>
                <tr>
                  <td></td>
                  <td>Meal#4</td>
                </tr>
                <tr>
                  <th>"ետճաշիկ"</th>
                  <td>Meal#1</td>
                </tr>
                <tr>
                  <td></td>
                  <td>Meal#2</td>
                </tr>

                <tr>
                    <th>Breakfast</th>
                    <th>Tuesday</th>
                </tr>
                <tr>
                  <td></td>
                  <td>Meal#1</td>
                </tr>
                <tr>
                  <td></td>
                  <td>Meal#2</td>
                </tr>
                <tr>
                  <td></td>
                  <td>Meal#3</td>
                </tr>
                  <tr>
                    <th>Lunch</th>
                    <td>Meal#1</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>Meal#2</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>Meal#3</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>Meal#4</td>
                  </tr>
                  <tr>
                    <th>"ետճաշիկ"</th>
                    <td>Meal#1</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>Meal#2</td>
                  </tr>

                  <tr>
                      <th>Breakfast</th>
                      <th>Wednesday</th>
                  </tr>
                  <tr>
                    <td></td>
                    <td>Meal#1</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>Meal#2</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td>Meal#3</td>
                  </tr>
                    <tr>
                      <th>Lunch</th>
                      <td>Meal#1</td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>Meal#2</td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>Meal#3</td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>Meal#4</td>
                    </tr>
                    <tr>
                      <th>"ետճաշիկ"</th>
                      <td>Meal#1</td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>Meal#2</td>
                    </tr>

                    <tr>
                        <th>Breakfast</th>
                        <th>Thursday</th>
                    </tr>
                    <tr>
                      <td></td>
                      <td>Meal#1</td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>Meal#2</td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>Meal#3</td>
                    </tr>
                      <tr>
                        <th>Lunch</th>
                        <td>Meal#1</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td>Meal#2</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td>Meal#3</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td>Meal#4</td>
                      </tr>
                      <tr>
                        <th>"ետճաշիկ"</th>
                        <td>Meal#1</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td>Meal#2</td>
                      </tr>

                      <tr>
                          <th>Breakfast</th>
                          <th>Friday</th>
                      </tr>
                      <tr>
                        <td></td>
                        <td>Meal#1</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td>Meal#2</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td>Meal#3</td>
                      </tr>
                        <tr>
                          <th>Lunch</th>
                          <td>Meal#1</td>
                        </tr>
                        <tr>
                          <td></td>
                          <td>Meal#2</td>
                        </tr>
                        <tr>
                          <td></td>
                          <td>Meal#3</td>
                        </tr>
                        <tr>
                          <td></td>
                          <td>Meal#4</td>
                        </tr>
                        <tr>
                          <th>"ետճաշիկ"</th>
                          <td>Meal#1</td>
                        </tr>
                        <tr>
                          <td></td>
                          <td>Meal#2</td>
                        </tr>

                        <tr>
                            <th>Breakfast</th>
                            <th>Saturday</th>
                        </tr>
                        <tr>
                          <td></td>
                          <td>Meal#1</td>
                        </tr>
                        <tr>
                          <td></td>
                          <td>Meal#2</td>
                        </tr>
                        <tr>
                          <td></td>
                          <td>Meal#3</td>
                        </tr>
                          <tr>
                            <th>Lunch</th>
                            <td>Meal#1</td>
                          </tr>
                          <tr>
                            <td></td>
                            <td>Meal#2</td>
                          </tr>
                          <tr>
                            <td></td>
                            <td>Meal#3</td>
                          </tr>
                          <tr>
                            <td></td>
                            <td>Meal#4</td>
                          </tr>
                          <tr>
                            <th>"ետճաշիկ"</th>
                            <td>Meal#1</td>
                          </tr>
                          <tr>
                            <td></td>
                            <td>Meal#2</td>
                          </tr>
            </table>
        </v-card-text>
      </v-card>
      </blockquote>
    </v-flex>
  </v-layout>
</template>
